#pragma once

enum LOGIN_PACKET_MAIN_CMD {
    eCMD_SYSTEM = 1,
    eCMD_LOGIN = 2,
    eCMD_CHARACTER = 3,
    eCMD_WORLD = 4,
    eCMD_CHANNEL = 241,
    eCMD_SERVER = 242,
    eCMD_MONITOR = 247,
};

enum SYSTEM_PACKET_SUB_CMD {
    eSUB_CMD_OPTION_UPDATE = 0x02,
    eSUB_CMD_SYSTEM_XIGNCODE = 0x03,
    eSUB_CMD_SYSTEM_XIGNCODE_ERROR = 0x04,
    eSUB_CMD_SYSTEM_KEEP_ALIVE = 0x05,
    eSUB_CMD_SYSTEM_SG_TOKEN_UPDATE = 0x11,
    eSUB_CMD_SYSTEM_GAME_GUARD_AUTH = 0x12,
    eSUB_CMD_SYSTEM_GAME_GUARD_ERROR = 0x13,
};

enum LOGIN_PACKET_SUB_CMD {
    eSUB_CMD_LOGIN_REQ = 1,
    eSUB_CMD_LOGIN_RES = 2,
    eSUB_CMD_SERVER_LIST_REQ = 3,
    eSUB_CMD_SERVER_CONNECT_REQ = 5,
    eSUB_CMD_SERVER_CONNECT_RES = 0x11,
    eSUB_CMD_ENTER_SERVER_REQ = 0x13,
    eSUB_CMD_ENTER_WAIT_NOTIFY = 0x34,
    eSUB_CMD_ENTER_WAIT_CANCEL = 0x35,
};

enum CHARACTER_PACKET_SUB_CMD {
    eSUB_CMD_CREATE_CHARACTER_REQ = 0x01,
    eSUB_CMD_DELETE_CHARACTER_REQ = 0x02,
    eSUB_CMD_CHARACTER_CHANGE_SLOT = 0x06,
    eSUB_CMD_CHARACTER_REPRESENTATIVE_CHECK = 0x0D,
    eSUB_CMD_CHARACTER_REPRESENTATIVE_CHANGE = 0x0F,
    eSUB_CMD_CHARACTER_LIST_REQ = 0x11,
    eSUB_CMD_CHARACTER_LIST_RES = 0x12,
    eSUB_CMD_SELECT_CHARACTER_REQ = 0x13,
    eSUB_CMD_SELECT_CHARACTER_RES = 0x14,
    eSUB_CMD_CHARACTER_ENTER_PROLOGUE = 0x15,
    eSUB_CMD_SECOND_PASSWORD = 0x17,
    eSUB_CMD_ENTER_GAMESERVER_REQ = 0x21,
    eSUB_CMD_ENTER_GAMESERVER_RES = 0x22,
    eSUB_CMD_CHARACTER_CHECK_NAME = 0x57,
    eSUB_CMD_CHARACTER_CHANGE_SERVER_REQ = 0x60,
};

enum WORLD_PACKET_SUB_CMD {
    eSUB_CMD_WORLD_NULL = 0,
    eSUB_CMD_WORLD_ENTER_REQ = 1,
    eSUB_CMD_WORLD_ENTER_RES = 2,
    eSUB_CMD_WORLD_CUR_DATE = 3,
    eSUB_CMD_WORLD_VERSION = 4,
    eSUB_CMD_WORLD_OBJECT_REQ = 6,
    eSUB_CMD_WORLD_WARP_REQ = 7,
    eSUB_CMD_WORLD_WARP_RES = 8,
    eSUB_CMD_WORLD_WARP_ENABLE_RES = 9,
    eSUB_CMD_WORLD_GATE_ENABLE_RES = 10,
    eSUB_CMD_WORLD_CHECKSECTOR_REQ = 11,
    eSUB_CMD_WORLD_CHECKSECTOR_RES = 12,
    eSUB_CMD_WORLD_WARP_OUT_REQ = 13,
    eSUB_CMD_WORLD_WARP_MAZE_RES = 14,
    eSUB_CMD_WORLD_WARP_MAZE_TIME_RES = 15,
    eSUB_CMD_IN_INFO_PC = 17,
    eSUB_CMD_OUT_INFO_PC = 18,
    eSUB_CMD_IN_INFO_NPC = 19,
    eSUB_CMD_OUT_INFO_NPC = 20,
    eSUB_CMD_IN_INFO_MONSTER = 21,
    eSUB_CMD_OUT_INFO_MONSTER = 22,
    eSUB_CMD_IN_INFO_SPAWNBOX = 24,
    eSUB_CMD_WORLD_GAME_OUT = 25,
    eSUB_CMD_OTHER_INFOS_PC = 33,
    eSUB_CMD_OTHER_INFOS_NPC = 34,
    eSUB_CMD_OTHER_INFOS_MONSTER = 35,
    eSUB_CMD_OUT_OTHER_INFOS_PC = 36,
    eSUB_CMD_MOVER_INFO_REQ = 49,
    eSUB_CMD_WORLD_ENTER_BATTLECRY = 50,
    eSUB_CMD_WORLD_ESCAPE = 51,
    eSUB_CMD_WORLD_DISTRICT_TRANSPORT_REQ = 64,
    eSUB_CMD_MAZE_CREATE_REQ = 65,
    eSUB_CMD_MAZE_CREATE_RES = 66,
    eSUB_CMD_ENTER_MAZE_LIMIT_COUNT_LOAD = 67,
    eSUB_CMD_ENTER_MAZE_LIMIT_COUNT_RESET = 68,
    eSUB_CMD_ENTER_MAZE_LIMIT_COUNT_UPDATE = 69,
    eSUB_CMD_ENTER_MAZE_LIMIT_COUNT_GROUP_LOAD = 70,
    eSUB_CMD_ENTER_MAZE_LIMIT_COUNT_GROUP_RESET = 71,
    eSUB_CMD_ENTER_MAZE_LIMIT_COUNT_GROUP_UPDATE = 72,
    eSUB_CMD_WORLD_ENTER_MAP_PC = 81,
    eSUB_CMD_WORLD_EXIT_MAP_PC = 82,
    eSUB_CMD_WORLD_CHANGE_PACKET_OPTIMIZATION = 96,
    eSUB_CMD_WORLD_SKIP_IN_TUTORIAL02_REQ = 97,
    eSUB_CMD_WORLD_END = 128,
};

enum CHANNEL_PACKET_SUB_CMD {
    eSUB_CMD_CHANNEL_INFO = 0x01,
    eSUB_CMD_CHANNEL_CHANGE = 0x02,
};

enum CHARACTER_DB_SUB_CMD {
    eSUB_SQL_CHARACTER_LIST = 0x01,
    eSUB_SQL_CHARACTER_CREATE = 0x02,
    eSUB_SQL_CHARACTER_DELETE = 0x03,
    eSUB_SQL_CHARACTER_CHECK_NAME = 0x04,
    eSUB_SQL_CHARACTER_CHANGE_SLOT = 0x06,
    eSUB_SQL_CHARACTER_REPRESENTATIVE_CHECK = 0x07,
    eSUB_SQL_CHARACTER_REPRESENTATIVE_CHANGE = 0x08,
    eSUB_SQL_ENTER_GAMESERVER = 0x21,
    eSUB_SQL_CHARACTER_SELECT = 0x22,
    eSUB_SQL_SECOND_PW_CONTINUE = 0x34,
    eSUB_SQL_SECOND_PW_CREATE = 0x35,
    eSUB_SQL_SECOND_PW_CHECK = 0x36,
    eSUB_SQL_SECOND_PW_STATE_CHECK = 0x37,
};

enum E_SUB_CMD_SERVER {
    eSUB_CMD_SERVER_NULL = 0,
    eSUB_CMD_SERVER_ADD = 1,
    eSUB_CMD_SERVER_DELETE = 2,
    eSUB_CMD_SERVER_UPDATE = 3,
    eSUB_CMD_SERVER_TO_RELAY = 5,
    eSUB_CMD_SERVER_FROM_RELAY = 6,
    eSUB_CMD_SERVER_WORLD_INFO = 7,
    eSUB_CMD_SERVER_SHUT_DOWN = 8,
    eSUB_CMD_SERVER_TIME_EVENT = 9,
    eSUB_CMD_SERVER_CHANGE_CHANNEL = 0x10,
    eSUB_CMD_SERVER_CHANNEL_UPDATE_ALL = 0x11,
    eSUB_CMD_SERVER_CHANNEL_UPDATE = 0x12,
    eSUB_CMD_SERVER_REPORT_STATUS = 0x13,
    eSUB_CMD_SERVER_VALUE_EVENT = 0x14,
    eSUB_CMD_SERVER_CASH_SHOP_BANNER = 0x15,
    eSUB_CMD_SERVER_CREATE_MAZE_REQ = 0x21,
    eSUB_CMD_SERVER_CREATE_MAZE_RES = 0x22,
    eSUB_CMD_SERVER_ENTER_MAP = 0x31,
};

enum E_SUB_CMD_SERVER_USER {
    eSUB_CMD_SERVER_USER_SELECT_CHARACTER = 0x01,
    eSUB_CMD_SERVER_USER_LOGIN = 0x02,
    eSUB_CMD_SERVER_USER_LOGOUT = 0x03,
    eSUB_CMD_SERVER_USER_UPDATE_MAP = 0x04,
    eSUB_CMD_SERVER_USER_ENTER_SERVER = 0x14,
    eSUB_CMD_SERVER_USER_TRADE_PASSWORD_STATE = 0x27,
    eSUB_CMD_SERVER_CHECK_SESSION_ID = 0x32,
    eSUB_CMD_SERVER_USER_UPDATE_AUTH_TYPE = 0x35,
};

enum E_SUB_CMD_MONITOR {
    eSUB_CMD_MONITOR_NULL = 0,
    eSUB_CMD_MONITOR_SYNC_SERVER_INFO_ALL = 1,
    eSUB_CMD_MONITOR_UPDATE_SERVER_INFO = 2,
    eSUB_CMD_MONITOR_UPDATE_MAZE_INFO = 3,
    eSUB_CMD_MONITOR_DELETE_SERVER = 4,
    eSUB_CMD_MONITOR_END = 128,
};
