#####################################################################################
# log4cxx 설정 파일
# level : DEBUG < INFO < ERROR
#####################################################################################


#------------------------------------------------------------------------------------
#concole appender설정
#------------------------------------------------------------------------------------
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=[%d{%y-%m-%d %H:%M:%S}] [%c][%p] %m%n

#------------------------------------------------------------------------------------
#로그인 appender 설정( 날짜별 파일. 파일의 최대 용량은 50MB. 백업은 1개 )
#------------------------------------------------------------------------------------
log4j.appender.D1 = org.apache.log4j.DailyRollingFileAppender
log4j.appender.D1.DatePattern = '.'yyyy-MM-dd
log4j.appender.D1.File = ./Log/LoginServer.log
log4j.appender.D1.append = true
log4j.appender.D1.MaxFileSize = 50MB
log4j.appender.D1.MaxBackupIndex = 1
log4j.appender.D1.ImmediateFlush= false
log4j.appender.D1.BufferedIO	= true
log4j.appender.D1.layout = org.apache.log4j.PatternLayout
log4j.appender.D1.layout.ConversionPattern =[%d{%y-%m-%d %H:%M:%S}] [%c][%p] %m%n

#------------------------------------------------------------------------------------
# 채널 로그파일 appender 설정( 날짜별 파일. 파일의 최대 용량은 50MB. 백업은 1개 )
#------------------------------------------------------------------------------------
log4j.appender.D2 = org.apache.log4j.DailyRollingFileAppender
log4j.appender.D2.DatePattern = '.'yyyy-MM-dd
log4j.appender.D2.File = ./Log/ChannelServer.log
log4j.appender.D2.append = true
log4j.appender.D2.MaxFileSize = 50MB
log4j.appender.D2.MaxBackupIndex = 1
log4j.appender.D2.ImmediateFlush= false
log4j.appender.D2.BufferedIO	= true
log4j.appender.D2.layout = org.apache.log4j.PatternLayout
log4j.appender.D2.layout.ConversionPattern =[%d{%y-%m-%d %H:%M:%S}] %m%n


#------------------------------------------------------------------------------------
# 인던 appender 설정( 날짜별 파일. 파일의 최대 용량은 50MB. 백업은 1개 )
#------------------------------------------------------------------------------------
log4j.appender.D3 = org.apache.log4j.DailyRollingFileAppender
log4j.appender.D3.DatePattern = '.'yyyy-MM-dd
log4j.appender.D3.File = ./Log/GameServer.log
log4j.appender.D3.append = true
log4j.appender.D3.MaxFileSize = 50MB
log4j.appender.D3.MaxBackupIndex = 1
log4j.appender.D3.ImmediateFlush= false
log4j.appender.D3.BufferedIO	= true
log4j.appender.D3.layout = org.apache.log4j.PatternLayout
log4j.appender.D3.layout.ConversionPattern =[%d{%y-%m-%d %H:%M:%S}] [%c][%p] %m%n

#------------------------------------------------------------------------------------
# 중계 appender 설정( 날짜별 파일. 파일의 최대 용량은 50MB. 백업은 1개 )
#------------------------------------------------------------------------------------
log4j.appender.D4 = org.apache.log4j.DailyRollingFileAppender
log4j.appender.D4.DatePattern = '.'yyyy-MM-dd
log4j.appender.D4.File = ./Log/Relay.log
log4j.appender.D4.append = false
log4j.appender.D4.MaxFileSize = 50MB
log4j.appender.D4.MaxBackupIndex = 1
log4j.appender.D4.ImmediateFlush= false
log4j.appender.D4.BufferedIO	= true
log4j.appender.D4.layout = org.apache.log4j.PatternLayout
log4j.appender.D4.layout.ConversionPattern =[%d{%y-%m-%d %H:%M:%S}] [%c][%p] %m%n

#------------------------------------------------------------------------------------
# 통계용 로그파일 appender 설정( 날짜별 파일. 파일의 최대 용량은 50MB. 백업은 1개 )
#------------------------------------------------------------------------------------
log4j.appender.D5 = org.apache.log4j.DailyRollingFileAppender
log4j.appender.D5.DatePattern = '.'yyyy-MM-dd
log4j.appender.D5.File = ./Log/System.log
log4j.appender.D5.append = true
log4j.appender.D5.MaxFileSize = 50MB
log4j.appender.D5.MaxBackupIndex = 1
log4j.appender.D5.ImmediateFlush= false
log4j.appender.D5.BufferedIO	= true
log4j.appender.D5.layout = org.apache.log4j.PatternLayout
log4j.appender.D5.layout.ConversionPattern =[%d{%y-%m-%d %H:%M:%S}] %m%n

#------------------------------------------------------------------------------------
# 컨텐츠 로그파일 appender 설정( 날짜별 파일. 파일의 최대 용량은 50MB. 백업은 1개 )
#------------------------------------------------------------------------------------
log4j.appender.D6 = org.apache.log4j.DailyRollingFileAppender
log4j.appender.D6.DatePattern = '.'yyyy-MM-dd
log4j.appender.D6.File = ./Log/contents.log
log4j.appender.D6.append = true
log4j.appender.D6.MaxFileSize = 50MB
log4j.appender.D6.MaxBackupIndex = 1
log4j.appender.D6.ImmediateFlush= false
log4j.appender.D6.BufferedIO	= true
log4j.appender.D6.layout = org.apache.log4j.PatternLayout
log4j.appender.D6.layout.ConversionPattern =[%d{%y-%m-%d %H:%M:%S}] %m%n

#------------------------------------------------------------------------------------
# 채널 로그파일 appender 설정( 날짜별 파일. 파일의 최대 용량은 50MB. 백업은 1개 )
#------------------------------------------------------------------------------------
log4j.appender.D7 = org.apache.log4j.DailyRollingFileAppender
log4j.appender.D7.DatePattern = '.'yyyy-MM-dd
log4j.appender.D7.File = ./Log/Item.log
log4j.appender.D7.append = true
log4j.appender.D7.MaxFileSize = 50MB
log4j.appender.D7.MaxBackupIndex = 1
log4j.appender.D7.ImmediateFlush= false
log4j.appender.D7.BufferedIO	= true
log4j.appender.D7.layout = org.apache.log4j.PatternLayout
log4j.appender.D7.layout.ConversionPattern =[%d{%y-%m-%d %H:%M:%S}] %m%n

#------------------------------------------------------------------------------------
# AI 로그파일 appender 설정( 날짜별 파일. 파일의 최대 용량은 50MB. 백업은 1개 )
#------------------------------------------------------------------------------------
log4j.appender.D8 = org.apache.log4j.DailyRollingFileAppender
log4j.appender.D8.DatePattern = '.'yyyy-MM-dd
log4j.appender.D8.File = ./Log/AI.log
log4j.appender.D8.append = true
log4j.appender.D8.MaxFileSize = 50MB
log4j.appender.D8.MaxBackupIndex = 1
log4j.appender.D8.ImmediateFlush= false
log4j.appender.D8.BufferedIO	= true
log4j.appender.D8.layout = org.apache.log4j.PatternLayout
log4j.appender.D8.layout.ConversionPattern =[%d{%y-%m-%d %H:%M:%S}] %m%n

log4j.debug = false

#------------------------------------------------------------------------------
#로그인 서버
#------------------------------------------------------------------------------
log4j.logger.game.login = DEBUG, stdout, D1

#------------------------------------------------------------------------------
#채녈 서버 로그 설정
#------------------------------------------------------------------------------
log4j.logger.game.channel = DEBUG, stdout, D2

#------------------------------------------------------------------------------
#게임 서버 로그 설정
#------------------------------------------------------------------------------
log4j.logger.game.maze = DEBUG, stdout, D3

#------------------------------------------------------------------------------
#중계 관련 로그 설정
#------------------------------------------------------------------------------
log4j.logger.game.relay = DEBUG, stdout, D4

#------------------------------------------------------------------------------
#아이템 관련 로그 설정
#------------------------------------------------------------------------------
log4j.logger.game.item = DEBUG, stdout, D7

#------------------------------------------------------------------------------
#파티 관련 로그 설정
#------------------------------------------------------------------------------
log4j.logger.game.party = DEBUG, stdout, D2

#------------------------------------------------------------------------------
#스킬 관련 로그 설정
#------------------------------------------------------------------------------
log4j.logger.game.skill = DEBUG, stdout, D2

#------------------------------------------------------------------------------
# Quest 관련 로그 설정
#------------------------------------------------------------------------------
log4j.logger.game.quest = DEBUG, stdout, D6

#------------------------------------------------------------------------------
# System 관련 로그 설정
#------------------------------------------------------------------------------
log4j.logger.game.system = DEBUG, stdout, D5

