#####################################################################################
# log4cxx 설정 파일
# level : DEBUG < INFO < ERROR
#####################################################################################


#------------------------------------------------------------------------------------
#concole appender설정
#------------------------------------------------------------------------------------
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=[%d{%y-%m-%d %H:%M:%S}] [%c][%p] %m%n

#------------------------------------------------------------------------------------
#SYSTEM appender 설정( 날짜별 파일. 파일의 최대 용량은 50MB. 백업은 1개 )
#------------------------------------------------------------------------------------
log4j.appender.D1 = org.apache.log4j.DailyRollingFileAppender
log4j.appender.D1.DatePattern = '.'yyyy-MM-dd
log4j.appender.D1.File = ./Log/Game/System.log
log4j.appender.D1.append = true
log4j.appender.D1.MaxFileSize = 50MB
log4j.appender.D1.MaxBackupIndex = 1
log4j.appender.D1.ImmediateFlush= false
log4j.appender.D1.BufferedIO	= true
log4j.appender.D1.BufferSize	= 80000
log4j.appender.D1.layout = org.apache.log4j.PatternLayout
log4j.appender.D1.layout.ConversionPattern =[%d{%y-%m-%d %H:%M:%S}] [%c][%p] %m%n

#------------------------------------------------------------------------------------
# GAME appender 설정( 날짜별 파일. 파일의 최대 용량은 50MB. 백업은 1개 )
#------------------------------------------------------------------------------------
log4j.appender.D2 = org.apache.log4j.DailyRollingFileAppender
log4j.appender.D2.DatePattern = '.'yyyy-MM-dd
log4j.appender.D2.File = ./Log/Game/Game.log
log4j.appender.D2.append = true
log4j.appender.D2.MaxFileSize = 50MB
log4j.appender.D2.MaxBackupIndex = 1
log4j.appender.D2.ImmediateFlush= false
log4j.appender.D2.BufferedIO	= true
log4j.appender.D2.BufferSize	= 80000
log4j.appender.D2.layout = org.apache.log4j.PatternLayout
log4j.appender.D2.layout.ConversionPattern =[%d{%y-%m-%d %H:%M:%S}] %m%n


#------------------------------------------------------------------------------------
# 중계 appender 설정( 날짜별 파일. 파일의 최대 용량은 50MB. 백업은 1개 )
#------------------------------------------------------------------------------------
log4j.appender.D3 = org.apache.log4j.DailyRollingFileAppender
log4j.appender.D3.DatePattern = '.'yyyy-MM-dd
log4j.appender.D3.File = ./Log/Game/Relay.log
log4j.appender.D3.append = false
log4j.appender.D3.MaxFileSize = 50MB
log4j.appender.D3.MaxBackupIndex = 1
log4j.appender.D3.ImmediateFlush= false
log4j.appender.D3.BufferedIO	= true
log4j.appender.D3.BufferSize	= 80000
log4j.appender.D3.layout = org.apache.log4j.PatternLayout
log4j.appender.D3.layout.ConversionPattern =[%d{%y-%m-%d %H:%M:%S}] [%c][%p] %m%n


log4j.debug = false


#------------------------------------------------------------------------------
# System 관련 로그 설정
#------------------------------------------------------------------------------
log4j.logger.game.system = DEBUG, stdout, D1

#------------------------------------------------------------------------------
#게임 관련 로그 설정
#------------------------------------------------------------------------------
log4j.logger.game.game = DEBUG, stdout, D2

#------------------------------------------------------------------------------
#게임 관련 로그 설정
#------------------------------------------------------------------------------
log4j.logger.game.contents = DEBUG, stdout, D2

#------------------------------------------------------------------------------
#아이템 관련 로그 설정
#------------------------------------------------------------------------------
log4j.logger.game.item = DEBUG, stdout, D2

#------------------------------------------------------------------------------
#파티 관련 로그 설정
#------------------------------------------------------------------------------
log4j.logger.game.party = DEBUG, stdout, D2

#------------------------------------------------------------------------------
#스킬 관련 로그 설정
#------------------------------------------------------------------------------
log4j.logger.game.skill = DEBUG, stdout, D2

#------------------------------------------------------------------------------
# Quest 관련 로그 설정
#------------------------------------------------------------------------------
log4j.logger.game.quest = DEBUG, stdout, D2

#------------------------------------------------------------------------------
#중계 관련 로그 설정
#------------------------------------------------------------------------------
log4j.logger.game.relay = DEBUG, stdout, D3




